[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/go/:slug"
  to = "/.netlify/functions/go?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "https://cedric-rancier.fr/"
  status = 302
  force = true
